spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10cDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: simple-transfer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    url: jdbc:oracle:thin:@localhost:1521:XE
    user: system
    password: oracle
    schemas: public
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        kafka: debug
